namespace: paperdebugger-dev
openai_api_key: sk-dummy-OPENAI_API_KEY
jwt_signing_key: paperdebugger
ghcr_docker_config: dummy-ghcr-docker-config
cloudflare_tunnel_token: dummy-cloudflare-tunnel-token

paperdebugger:
  image: ghcr.io/paperdebugger/sharelatex-paperdebugger:latest

paperdebuggerMcpServer:
  image: ghcr.io/paperdebugger/paperdebugger-mcp-server:main-14409c5

paperdebuggerXtraMcpServer:
  image: ghcr.io/paperdebugger/xtragpt-mcp-server:main-cfe6e39

mongo:
  in_cluster: true
  uri: "" # if in_cluster is false, use the external mongo instead
  image: mongo:latest
